include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Additional lint rules
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    prefer_single_quotes: true
    sort_constructors_first: true
    use_key_in_widget_constructors: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
